.TH tbt 1 "April 8, 2007" "tbt"

.SH NAME
tbt \- Time Based Text

.SH SYNOPSIS
.B tbt [options] [file]

.SH DESCRIPTION
.B tbt - Time Based Text

To vehicle more human-input information in written text.

Record performance time of written text and vehicle it as additional information: saving and reproducing every single action during the composition of a text let us vehicle emphasis in written communication.

As this simple concept, our implementation is also kept very minimalistic while we welcome programmers to embed it in communication applications, as in emails, blogs, visual poetry, slides and what not.

Beware this software is hacky, u need to love text. A manual page is provided and commandline formulas to be casted in a terminal.

This software is written in thread-safe POSIX C++ and can be ported to most platforms, it provides a real-time recorder for serial timed data, recording 64bit tuples key/msec with low-latency. Included are programs providing a text console interface for the user to experiment with keyboard.

A Web application written in PHP/MySQL and Ajax could be used to publish TBT written into the world wide web.

.SH PROTOCOL

In the .tbt format, text is saved with a timestamp for each letter:
   _________ ___________ 
  |  u-int  |   u-int   |
  |  64bit  |   64bit   |    m-seconds = 1/1000 of a second
   --------- -----------
  |  char   | m-seconds |    char = ASCII or higher bit char code
   --------- -----------
  |    Total: 128bit    |
   ---------------------

However export to different formats is planned including generation of web-ready code in HTML and Javascript, a daemon to provide timed input thru a socket on the network (TCP/IP) and what not.

Input is captured from the console, but can be extended to intercept any application using some h4x0r keylogging technique on different OS.

.SH OPTIONS

.B
.IP "-h"
Display a help text and quit
.B
.IP "-v"
Display version and quit
.B
.IP "-D \fI<number>\fR"
Set verbosity level, the default value is 1
.B
.IP "-c"
Use the S-Lang console interface
.B
.IP "-r"
record tbt - option alias: rectext
.B
.IP "-p"
playback tbt - option alias: playtext
.B
.IP "-m"
mail composer - option alias: recmail
.B
.IP "-s \fI<format_name>\fR"
save format in [ bin | ascii | html ]. Default is bin.. Default is bin.

The binary mode will store a binary file you can play with the playtext command.

The html mode will produce a simple html page, in which your text will be played. For further information about the html mode please the the README.html file.

The ascii mode produces pure ascii text file, one character per line, with the information about the key pressed, and the timestamp.

.SH EXAMPLES

.B
.IP "Howto record a tbt in binary format"

$ rectext -s bin mytext.tbt

.B
.IP "Howto play a tbt binary file"

$ playtext mytext.tbt

.B
.IP "Howto record a tbt in ascii mode"

$ rectext -s ascii mytext.txt

.B
.IP "Howto record a tbt in html mode"

$ rectext -s html mytext.html

.SH NOTES
The first integration provided for TBT is with Mutt \fIhttp://www.mutt.org\fR the Mail User Agent popular among text console users.
For further information please read the README.mutt file.

.SH BUGS
Everyone is encouraged to test this software and report bugs!
Send remarks and patches to http://dyne.org/hackers_contact.php or get in touch with coders via irc.freenode.net channel #dyne

.SH AUTHORS
Ideated by Jaromil & Jodi
.br
commissioned by the Impakt.nl festival

POSIX C++ code: Denis 'Jaromil' Rojo <\fIjaromil@dyne.org\fR>
.br
PHP/Javascript code: Angelo 'pallotron' Failla <\fIpallotron@freaknet.org\fR>
Webdesign: O.K. Parking - www.ok-parking.nl

Thanks to: Florian Cramer, Angelo 'Pallotron' Failla, Annet Dekker,
Giacomo Verde, Roberto Castello, Andrea 'Alpt' Lo Pumo

.SH COPYING
Copyright (c) 2001-2006 Denis Roio <\fIjaromil@dyne.org\fR>
.br
Copyright (c) 2001-2007 Angelo Failla <\fIpallotron@freaknet.org\fR>

Permission is granted to copy, distribute and/or modify this manual under the terms of the GNU Free Documentation License, Version 1.1 or any later version published by the Free Software Foundation. Permission is granted to make and distribute verbatim copies of this manual page provided the above copyright notice and this permission notice are preserved on all copies.

.SH AVAILABILITY
The most recent version of tbt sourcecode and up to date documentation is always available for download from \fIhttp://tbt.dyne.org\fR.

.SH SEE ALSO

* README.mutt
* README.html
