
all:
	emacs -Q -no-site-file -batch -l muse-config.el  \
		-f muse-project-batch-publish "TBT"


clean:
	emacs -Q -no-site-file -batch -l muse-config.el  \
		-f muse-project-delete-output-files  "TBT"


