<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>

	<title>TBT</title>
	<style type="text/css" media="all">
		@import "styles/default.css";
	</style>
	<script language="JavaScript" src="include/tbt-typewriter.js"></script>
	<script type="text/JavaScript">

		function MM_openBrWindow(theURL,winName,features) { //v2.0
		window.open(theURL,winName,features);
		}
		var bgcolorlist=new Array("#000000","#333333","#666666","#003333",
				"#660000","#660033","#663333","#333300","#000033");

	</script>
	<script language="JavaScript" src="include/site_texts.inc.js"></script>
	 <!--[if lt IE 7.]>
	<script defer type="text/javascript" src="include/third_part/pngfix.js"></script>
	<![endif]-->
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
</head>

<body class="mainbody">

<script type="text/javascript" src="include/third_part/wz_dragdrop.js"></script>
<script type="text/javascript" src="include/ajax-functions.js"></script>
<script language="JavaScript" src="include/js-functions.js"></script>
<div id="menu">

	<table width="1010px" border="0" cellpadding="0" cellspacing="0" class="andalemono">
	<tr>
		<td align="left" valign="top" class="andalemono">
			--<u>F</u>ILE /
			<a href="http://tbt.dyne.org/?info=download">Download TBT software</a> / 
			<span onClick="MM_openBrWindow('upload.php','Upload','width=350,height=400')"><a href="#">Upload your TBT</a></span> / 
			<u>S</u>EARCH : <form style="display: inline;" name="search" method="post" action="<?=$_SERVER['PHP_SELF'];?>?action=search"><input type="text" name="search_pattern" value="<? if($_GET['action']!="") echo $_POST['search_pattern']; ?>"/></form> / 
			<u>H</u>ELP / 
			<span onClick="printMsg(about_tbt_text)"><a href="#">About TBT</a></span> / 
			<span onClick="printMsg(info_tbt_text)"><a href="#">Info </a></span> /
			<a href="<?=$_SERVER['PHP_SELF'];?>">Show last 5 tbts</a></span> /
		</td>
	</tr>
	<tr>
		<td height="104" align="left" valign="top">&nbsp;</td>
	</tr>
	</table>

	<table width="100%" border="0" align="left" cellpadding="0" cellspacing="0">
	<tr class="andalemono">
		<td align="left" valign="top">--<a href="http://tbt.dyne.org/"><u>TIME BASED TEXT</u></a>--</td>
	</tr>
	</table>

</div>

<div style="position: absolute; width: 320px; top: 150px; left: 300px;">
<img src="images/tbt-wheel.png" />
</div>

<div id="res">
</div>

<script language="JavaScript">

	function MultiDimensionalArray(iRows,iCols) {
		var i;
		var j;
		var a = new Array(iRows);
		
		for (i=0; i < iRows; i++) { 
			a[i] = new Array(iCols); 
			for (j=0; j < iCols; j++) { 
				a[i][j] = ""; 
			} 
		}
		return(a);
	} 

	// the array of tbt's generated by php
	<?php
		include_once("include/db.inc.php");
		include_once("include/tbt-php.php");

		$TBT = new TBT_DB;

		$action=$_GET['action'];
		// in case of no action take the last 5 tbt files
		switch($action) {
			case "search":
				$search_pattern = $_POST['search_pattern'];
				$row = $TBT->search($search_pattern,10);
				break;
			default:
				$row = $TBT->get_n(5);
				break;
		}

		if($row!=false) {

			echo "tbt_array = MultiDimensionalArray(".((sizeof($row)-1)).",".(sizeof($row[0])).")\n";
			
			$i=0;
			foreach($row as $r) {
				if($r["file"]!="") {
					echo "tbt_array['$i']['id']=\"".$r["id"]."\"\n";
					echo "tbt_array['$i']['title']=\"".$r["title"]."\"\n";
					echo "tbt_array['$i']['author']=\"".$r["author"]."\"\n";
					echo "tbt_array['$i']['city']=\"".$r["city"]."\"\n";
					$TBT_JSRender = new TBT_JSRender($upload_dir."/".$r["file"]);
					echo "tbt_array['$i']['tbt']=".$TBT_JSRender->get_jsstr()."\n";
					echo "tbt_array['$i']['email']=\"".$r["email"]."\"\n";
					echo "tbt_array['$i']['datetime']=\"".$r["datetime"]."\"\n";
					$i++;
				}
			}
		}
	?>
	
	var max_result = 5
	var min_x = 40
	var max_x = 650

	var min_y = 40
	var max_y = 85

	var ran_y = new Array()
	var ran_x = new Array()
	var width  = new Array()
	var height = new Array()
	var i = 0

	function is_collision(i) {
		var j
		
		for(j=0;j<=i;j++) {
			if( ( (ran_x[i] > ran_x[j])             && (ran_x[i]             < ran_x[j] + width[j]) ) ||
			    ( (ran_y[i] > ran_y[j])             && (ran_y[i]             < ran_y[j] + height[j]) )  ||
				( (ran_x[i] + width[i]  > ran_x[j]) && (ran_x[i] + width[i]  < ran_x[j] + width[j] ) ) ||
			    ( (ran_y[i] + height[i] > ran_y[j]) && (ran_y[i] + height[i] < ran_y[j] + height[j]) ) ) return true;
		}
		return false;
	}

	function print_divs() {

	for(i=0; i<tbt_array.length; i++) {

		ran_y[i] = Math.floor(Math.random()*(max_y-min_y))+min_y
		ran_x[i] = Math.floor(Math.random()*(max_x-min_x))+min_x
		var str = '<div id="div_'+i+'" style="vertical-align: middle; background-color: #333; opacity: .5; '
		if(msieversion()<7 && msieversion()!=0) str += 'filter:alpha(opacity=50);'
		str += ' border: 1px solid; visibility: hidden; z-index: '+(i+1)+
			'; position: absolute; left:'+ran_x[i]+'px; top:'+ran_y[i]+ 'px;"><img style="cursor:move;" src="images/hand.png"/>'+
			'<span class="andalemono" onclick="playTBT(tbt_array['+i+']);"> <a href="#">'+tbt_array[i]['title']+'</a></span></div>'
		document.getElementById("res").innerHTML += str
		if(msieversion()<7 && msieversion()!=0) correctPNG()
		width[i]  = document.getElementById("div_"+i).clientWidth
		height[i] = document.getElementById("div_"+i).clientHeight
		if(i>=1) {
			while(is_collision(i)) {
				ran_y[i] = Math.floor(Math.random()*(max_y-min_y))+min_y
				ran_x[i] = Math.floor(Math.random()*(max_x-min_x))+min_x
			}
		}
		document.getElementById("div_"+i).style.left = ran_x[i]
		document.getElementById("div_"+i).style.top  = ran_y[i]
		document.getElementById("div_"+i).style.visibility = "visible"
		if(i+1 == max_result) break;

	}

	}

	print_divs()

	<?
		$str = "SET_DHTML(";
		for($j=0; $j<$i; $j++) {
			$str .= "\"div_$j\",";
		}
		$str .= ")\n";
		$str = str_replace(",)",")",$str);
		echo $str;
	?>

</script>

<div style="position: absolute; width: 320px; top: 150px; left: 10px;"  id="tbt_0"></div>
<div style="position: absolute; width: 320px; top: 150px; left: 350px;" id="tbt_1"></div>
<div style="position: absolute; width: 320px; top: 150px; left: 690px;" id="tbt_2"></div>

<script language="JavaScript">

	var total_counter = 0
	var row_counter = 0
	var tbt_related_array = null

	function playTBT(tbt_array) {

		if(total_counter % 3 == 0) {
			row_counter = 0
		}

		document.getElementById("tbt_2").innerHTML = document.getElementById("tbt_1").innerHTML
		document.getElementById("tbt_1").innerHTML = document.getElementById("tbt_0").innerHTML

		var related_string = ""
		var related_array  = ""
		var xmlrequest = null
		request = CreateXmlHttpReq2()
		request.open("GET","xml_tbt_info.php?action=related&id="+tbt_array['id'],false);
		request.send(null);
		if (request.readyState == 4 && request.status == 200) {
			var response = request.responseXML.documentElement;
			x=response.getElementsByTagName("num")
			num = x[0].firstChild.data
			if(num>0) {
				x=response.getElementsByTagName("tbt")
				for(i=0;i<x.length;i++) {
					var id = x[i].getElementsByTagName("id")[0].firstChild.data
					var author   = x[i].getElementsByTagName("author")[0].firstChild.data
					var title    = x[i].getElementsByTagName("title")[0].firstChild.data
					var email    = x[i].getElementsByTagName("email")[0].firstChild.data
					var city     = x[i].getElementsByTagName("city")[0].firstChild.data
					var datetime = x[i].getElementsByTagName("datetime")[0].firstChild.data
					var tbt      = x[i].getElementsByTagName("data")[0].firstChild.data
					related_string += "<span onclick='playTBT_noarray("+
						id+",\""+author+"\",\""+title+"\",\""+email+"\",\""+city+"\",\""+datetime+"\","+tbt+
						")'><a href='#'>"+title+" by "+author+"</a></span><br/>"
				}
			} else related_string = "nothing"
		}

		document.getElementById("tbt_"+row_counter).innerHTML = 
		"<div style='border-top: 1px solid black; border-left: 1px solid black; border-right: 1px solid black; padding: 5px 5px 5px 5px; background-color:"+
		bgcolorlist[Math.floor(Math.random()*bgcolorlist.length)]+";'"+
		"class='couriersmall'><b>From: "+tbt_array['author']+" <br/>&lt;<a href=\"mailto:"+tbt_array['email']+"\">"+tbt_array['email']+"</a>&gt;<br/>"+
		"Title: "+tbt_array['title']+"<br/>"+
		"Date/Time: "+tbt_array['datetime']+"<br/>"+
		"City: "+tbt_array['city']+"<br/></b>"+
		"</div><div id='tbttext_"+row_counter+
		"' style='border-left: 1px solid black; border-top: 1px solid black; border-right: 1px solid black; padding: 5px 5px 5px 5px; background-color:"+
		bgcolorlist[Math.floor(Math.random()*bgcolorlist.length)]+ ";' class='couriersmall'></div>"+
		"<div style='border: 1px solid black; padding: 5px 5px 5px 5px; background-color:"+bgcolorlist[Math.floor(Math.random()*bgcolorlist.length)]+";'"+
		"class='couriersmall'>Related TBT's: <br/>"+related_string+"</div>"

		var tbt = new TBT()
		tbt.startTyping("tbttext_"+row_counter, tbt_array['tbt'])

		total_counter++
	}

	function playTBT_noarray(id,author,title,email,city,datetime,tbt) {

		var tbt_arr = new Array(7)

			tbt_arr['id'] = id
			tbt_arr['author'] = author
			tbt_arr['title'] = title
			tbt_arr['email'] = email
			tbt_arr['city'] = city
			tbt_arr['datetime'] = datetime
			tbt_arr['tbt'] = tbt

			playTBT(tbt_arr)
	}

	function printMsg(what) {

		if(total_counter % 3 == 0) {
			row_counter = 0
		}

		document.getElementById("tbt_2").innerHTML = document.getElementById("tbt_1").innerHTML
		document.getElementById("tbt_1").innerHTML = document.getElementById("tbt_0").innerHTML

		document.getElementById("tbt_"+row_counter).innerHTML=
			"</div><div id='tbttext_"+row_counter+
			"' style='border: 1px solid black; padding: 5px 5px 5px 5px; background-color:"+bgcolorlist[Math.floor(Math.random()*bgcolorlist.length)]+
			";' class='couriersmall'></div>"

		var tbt = new TBT()
		tbt.startTyping("tbttext_"+row_counter, what) 

		total_counter++
	}

</script>

</body>
</html>
